import Head from 'next/head'
import MainLayout from '../layouts/MainLayout'
import CardList from '../components/CardList/CardList'
import {useEffect, useState} from 'react'
import getData from './api'
import getConfig from 'next/config';

export const {publicRuntimeConfig: { FIRST_URL }} = getConfig();

export default function Home(props) {
  const [data, setData] = useState(props.data)


  return (
    <MainLayout>
      <Head>
        <title>2APICK</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CardList
        animeItems={data}
      />
    </MainLayout>
  )
}

export const getStaticProps = async () => {
  const data = await getData(FIRST_URL)

  return {
    props: data
  }
}
