import Head from 'next/head'
import Button from '../components/Button/Button'
import MainLayout from '../layouts/MainLayout'
import Card from '../components/Card/Card'

export default function Home() {

  return (
    <MainLayout>
      <Head>
        <title>2A PICK</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Button>
          принять
        </Button>

        <Card
          width="250"
          hiegth="380"
        />

      </div>


    </MainLayout>
  )
}
