import Head from 'next/head'
import MainLayout from '../layouts/MainLayout'
import CardList from '../components/CardList/CardList'
import axios from 'axios'
import {useState} from 'react'


export default function Home(props) {
  const [data, setData] = useState(props.data)

  return (
    <MainLayout>
      <Head>
        <title>2APICK</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CardList
        animeItems={data}
      />

    </MainLayout>
  )
}

export const getStaticProps = async () => {
  const response = await axios.get(process.env.NEXT_PUBLIC_BASE_URL + '10')
  return {
    props: response.data
  }
}
